### ISSUE TITLE
Add merged datasets functionality

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#1057]
Allows data from two or more forms to be represented as one form/endpoint.

The model will inherit from existing xform model. The difference are:  
- It will have its schema be a created from a combination of N+ xforms
- It will not accept submissions

*Requirements*
- [x] Add functionality in forms endpoint for creating merged dataset (may not be required)
- [ ] Generate Schema from existing xforms
- [x] Query data from child xforms
- [x] Use existing endpoints (`projects`, `forms`, `data`) to access/modify the form
- [x] Allows exports
- Integrations
  - [ ] Webhooks
  - [ ] Google sheets
  - [ ] Rapidpro
- [ ] HXL support
- [x] Will reflect changes (updates/deletions) in the parent datasets

**Comment by urbanslug** [comment]
# Implementation plan<a id="sec-1" name="sec-1"></a>

## Merged datasets<a id="sec-1-1" name="sec-1-1"></a>

### To do:<a id="sec-1-1-1" name="sec-1-1-1"></a>

-   Add a MergedXForm model
    -   [X] Subclass the XForm model
    -   [X] Extend it with an \`xforms\` field

-   Add MergedXFormViewset
    -   [X] Add a merged-dataset endpoint

-   Add MergedXFormSerializer
    -   [X] GET Create - takes {"xforms": ["list-of-xform-urls"], "name": "form-name-string", "project": "url-to-parent-project"}
    -   [X] POST Retreive a user's merged datasets - list and detail (data endpoint)
    -   [ ] PATCH Update - we can submit to a merged xform
    -   [ ] Expose an endpoint to retrieve merged dataset JSON and XML
    -   [ ] Expose a merged-dataset data endpoint to give data for specific merged dataset

-   Validate that: (serializer validation and model before save)
    -   [ ] name is a required field
    -   [ ] project is a required field
    -   [ ] A merged XForm is made of at least two xforms

-   Add permissions and authourization
    -   [ ] Inherit permissions from the project

**Comment by urbanslug** [comment]
### `ManyToManyField` v `OneToMany` for `xforms` in MergedXForm model.

---

##### OneToMany field
In this case django would create an merged xform relation with a foreign key field to reference a specific xform. It would however not be able to store more then one xform id. This means a merged xform would only reference a single xform. However, what we want is for a single merged xform to reference an arbitrary number of xforms.

`xform table`

| id    |  other | xform  | columns  | 
|-----|:------:|:------:|:---------:|
| 267 |   data  |   data  |    data     | 
| 377  |  data  |  data   |    data     |
| 487  |  data  | data    |    data     |

`merged xform table`

| id   | xform_id_foreign_key   | 
|----|:----------------------:|
| 1    | 267                               |
| 2    | 377                               |
| 3    | 478                               |

##### ManyToMany
A many to many field creates another table that references both the xforms and merged xforms table

`xform table`

| id    |  other | xform  | columns  | 
|-----|:------:|:------:|:---------:|
| 267 |   data  |   data  |    data     | 
| 377  |  data  |  data   |    data     |
| 487  |  data  | data    |    data     |

`merged xform table`

| id   | 
|----|
| 1    |
| 2    |
| 3    | 


`logger merged xform table`

| id |  merged_xform | xform |
|---|:---------------:|:------:|
| 1  |            1              |   267  |
| 2  |           1               |  377   |
| 3  |          2               | 267    |
| 4  |          2               | 487    |

This way when fetching the xforms for a merged dataset, we select the records where the merged xfrom value matches the id of the merged xform and get all the xform values for those records.

**Comment by ukanga** [comment]
closed by #1082
